const GITHUB_AUTH_TOKEN = "null"
const BOT_NUMBER = "94704147964"
const SESSION_ID = "PRABATH-MD~LFlSHY5S#WrarGykj8YMyMHGryzJy5LwwMuCeyAksJZ4c_PGA49w"


module.exports = {
GITHUB_AUTH_TOKEN,
BOT_NUMBER,
SESSION_ID
}
