const GITHUB_AUTH_TOKEN = "null"
const BOT_NUMBER = "null"
const SESSION_ID = ""


module.exports = {
GITHUB_AUTH_TOKEN,
BOT_NUMBER,94704147964
SESSION_ID PRABATH-MD~LFlSHY5S#WrarGykj8YMyMHGryzJy5LwwMuCeyAksJZ4c_PGA49w
}
